#!/usr/bin/env bash

# Note all experiments are conducted using the '--randomOverlap' approach for
# ball placement.

runStrongScaling=true         # set to 'true' to run strong scaling experiments
runWeakScaling=true           # set to 'true' to run weak scaling experiments
runBallFocusedApproach=true   # set to 'true' to run ball-focused approach
runStencilBasedApproach=true  # set to 'true' to run stencil-focused approach

nodecount=( 1 2 4 8 16 32)    # list of number of nodes to run experiments on 
algs=( 0)  # how to conduct ball focused version. 0 = w/ outer, synchronizing,
           # time-loop; 1 = w/ inner, non-synchronizing, time-loop
time_to_run=1000  # how long to run each simulation (in simulated seconds)

# Parameters to set for 'strong' scaling experiments; add to list to
# conduct additional experiments:
sqrt_els=( 1024)    # sqrt of number of pongers across all nodes
num_balls=( 1024)   # total number of balls across all nodes

# Parameters to set for 'weak' scaling experiments; add to list to
# conduct additional experiments:
sqrt_els_per_node=( 128)    # sqrt of number of pongers on each node
messages_per_node=( 512)    # number of balls to place on each node

# -----------------------------------------------------------------------------

set -e

(set -x; chpl --fast pingPongBallFocused.chpl)
(set -x; chpl --fast pingPongStencil.chpl)

if [[ "$runStrongScaling" == 'true' ]]; then
  echo '==== CONDUCTING STRONG SCALING EXPERIMENTS ===='

  if [[ "$runBallFocusedApproach" == 'true' ]]; then
    echo '-- RUNNING "BALL FOCUSED" APPROACH --'
    for alg in "${algs[@]}"; do
      for nc in "${nodecount[@]}"; do
        for pn_msg in "${num_balls[@]}"; do
          for pn_els in "${sqrt_els[@]}"; do
            (set -x; ./pingPongBallFocused -nl $nc --N=$pn_els --numDims=2 --randomOverlap=$pn_msg --timeToRun=$time_to_run --algorithm=$alg)
            echo ""
          done
        done
      done
    done
  fi

  if [[ "$runStencilBasedApproach" == 'true' ]]; then
    echo '-- NEXT RUNNING "STENCIL FOCUSED" APPROACH --'
    for alg in "${algs[@]}"; do
      for nc in "${nodecount[@]}"; do
        for pn_msg in "${num_balls[@]}"; do
          for pn_els in "${sqrt_els[@]}"; do
            (set -x; ./pingPongStencil -nl $nc --N=$pn_els --numDims=2 --randomOverlap=$pn_msg --timeToRun=$time_to_run)
            echo ""
          done
        done
      done
    done
  fi
fi

if [[ "$runWeakScaling" == 'true' ]]; then
  echo '==== CONDUCTING WEAK SCALING EXPERIMENTS ===='

  if [[ "$runBallFocusedApproach" == 'true' ]]; then
    echo '-- RUNNING "BALL FOCUSED" APPROACH --'
    for alg in "${algs[@]}"; do
      for nc in "${nodecount[@]}"; do
        for pn_msg in "${messages_per_node[@]}"; do
          for pn_els in "${sqrt_els_per_node[@]}"; do
            n=$(echo "(sqrt($pn_els*$pn_els*$nc))/1" | bc)
            nBalls=$(echo "($pn_msg*$nc)/1" | bc)
            (set -x; ./pingPongBallFocused -nl $nc --N=$n --numDims=2 --randomOverlap=$nBalls --timeToRun=$time_to_run --algorithm=$alg)
            echo ""
          done
        done
      done
    done
  fi

  if [[ "$runStencilBasedApproach" == 'true' ]]; then
    echo '-- NEXT RUNNING "STENCIL FOCUSED" APPROACH --'
    for nc in "${nodecount[@]}"; do
      for pn_msg in "${messages_per_node[@]}"; do
        for pn_els in "${sqrt_els_per_node[@]}"; do
          n=$(echo "(sqrt($pn_els*$pn_els*$nc))/1" | bc)
          nBalls=$(echo "($pn_msg*$nc)/1" | bc)
          (set -x; ./pingPongStencil -nl $nc --N=$n --numDims=2 --randomOverlap=$nBalls --timeToRun=$time_to_run)
          echo ""
        done
      done
    done
  fi
fi
