#!/bin/bash

# This tests that the json files generated by the chapel script will work when used as input to an SST simulation


set -x
set -e
sideLength=2
edgeDelay=50
rankCounts="1 2"
threadCounts="1 2"

make jsonGenerator

for rankCount in $rankCounts; do
  for threadCount in $threadCounts; do
    prefix=${sideLength}_${edgeDelay}_${rankCount}_${threadCount}
    outputPrefix=${prefix}_generated
    ./jsonGenerator -nl1 --rankCount=$rankCount --threadsPerRank=$threadCount \
      --sideLength=$sideLength --edgeDelay=$edgeDelay --timeToRun=100 \
      --randomOverlap 100 --outputPrefix=$outputPrefix
    srun -N $rankCount sst -n $threadCount --parallel-load $outputPrefix.json
  done
done